apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tpr2u-com-tls
spec:
  secretName: tpr2u-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tpr2u.com
  dnsNames:
    - tpr2u.com
    - www.tpr2u.com



